# -*- mode: ruby -*-
# vi: set ft=ruby :

# automatic set by build script 
$BOX = 'chef/debian-7.7'
$PDNSBOX = '../boxes/debian/debian-7.7/passivedns.box'

boxes = [
  { :name => :elastic,:ip => '192.168.33.111',:forward => 9200,:cpus => 2,:mem => 1024,:box => $BOX, :provision => 'provision_elastic.sh' },
  #{ :name => :rest,:ip => '192.168.33.112',:forward => 433,:cpus => 1,:mem => 256, :box => $BOX, :provision => 'build_rest' },
  { :name => :passivedns,:ip => '192.168.33.113',:cpus => 1,:mem => 256, :box => $PDNSBOX, :provision => 'provision_passivedns.sh' },
  ]


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    boxes.each do |opts|
        config.vm.define opts[:name] do |config|
            config.vm.box       = opts[:box]
            config.vm.synced_folder ".", "/vagrant", disabled:true
            config.vm.network  "private_network", ip: opts[:ip]
            config.vm.network  "forwarded_port", guest: opts[:forward], host: opts[:forward] if opts[:forward]
            config.vm.hostname = "%s.vagrant" % opts[:name].to_s
            config.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--cpus", opts[:cpus] ] if opts[:cpus]
                vb.customize ["modifyvm", :id, "--memory", opts[:mem] ] if opts[:mem]
            end
            config.vm.provision "shell", path: opts[:provision] if opts[:provision]
       end
    end
end
